PinterestApp/Controllers/BoardsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PinterestApp.Data;
using PinterestApp.Models;

namespace PinterestApp.Controllers
{
    [Authorize(Roles = "User,Admin")]
    public class BoardsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public BoardsController(
                                ApplicationDbContext context,
                                UserManager<ApplicationUser> userManager,
                                RoleManager<IdentityRole> roleManager
                                )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
                ViewBag.Alert = TempData["messageType"];
                ViewBag.Tip = TempData["messageIcon"].ToString();
            }
            var boards = db.Boards.Include("User").Include("SavedBookmarks.Bookmark").Where(b => b.UserId == _userManager.GetUserId(User));
            ViewBag.Boards = boards;
            return View();
        }
        [HttpPost]
        public IActionResult DeleteBookmark (int id)
        {
            SavedBookmark savedBookmark = db.SavedBookmarks.Include("Board").Where(sb => sb.Id == id).First();
            if(savedBookmark.Board.UserId == _userManager.GetUserId(User))
            {
                db.SavedBookmarks.Remove(savedBookmark);
                db.SaveChanges();
                return Redirect("/Boards/Show/" + savedBookmark.BoardId);
            }
            else
            {
                TempData["message"] = "Nu puteti sterge acest SavedBookmark";
                TempData["messageType"] = "alert-danger";
                TempData["messageIcon"] = "0";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Show(int id)
        {
            Board board = db.Boards.Include("SavedBookmarks.Bookmark")
                                   .Include("SavedBookmarks.Bookmark.User")
                                   .Where(b => b.Id == id)
                                   .Where(b => b.UserId == _userManager.GetUserId(User))
                                   .First();
            return View(board);
        }
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        public IActionResult New(Board board)
        {
            board.UserId = _userManager.GetUserId(User);
            if (ModelState.IsValid)
            {
                db.Boards.Add(board);
                db.SaveChanges();
                TempData["message"] = "Ati creat un nou Board!";
                TempData["messageType"] = "alert-success";
                TempData["messageIcon"] = "1";
                return RedirectToAction("Index");
            }
            else
            {
                return View(board);
            }
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Board board = db.Boards.Where(b => b.Id == id).First();
            //daca board-ul cu id-ul transmis este al userului curent putem face edit
            if (board.UserId == _userManager.GetUserId(User))
            {
                return View(board);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui board care nu va apartine";
                TempData["messageType"] = "alert-danger";
                TempData["messageIcon"] = "0";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Edit(int id, Board brd)
        {
            Board board = db.Boards.Find(id);
            if (ModelState.IsValid)
            {
                if (board.UserId == _userManager.GetUserId(User))
                {
                    board.Title = brd.Title;
                    db.SaveChanges();
                    TempData["message"] = "Ati editat cu succes board-ul";
                    TempData["messageType"] = "alert-success";
                    TempData["messageIcon"] = "1";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui board care nu va apartine";
                    TempData["messageType"] = "alert-danger";
                    TempData["messageIcon"] = "0";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(brd);
            }
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            Board board = db.Boards.Include("SavedBookmarks").Where(b => b.Id == id).First();
            if(board.UserId == _userManager.GetUserId(User))
            {
                db.Remove(board);
                db.SaveChanges();
                TempData["message"] = "Ati sters cu succes board-ul";
                TempData["messageType"] = "alert-success";
                TempData["messageIcon"] = "1";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui board care nu va apartine";
                TempData["messageType"] = "alert-danger";
                TempData["messageIcon"] = "0";
                return RedirectToAction("Index");
            }
        }

        private void SetAccessRights()
        {
            ViewBag.AfisareButoane = false;

            if (User.IsInRole("User"))
            {
                ViewBag.AfisareButoane = true;
            }

            ViewBag.EsteAdmin = User.IsInRole("Admin");

            ViewBag.UserCurent = _userManager.GetUserId(User);
        }
    }
}

PinterestApp/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PinterestApp.Data;
using PinterestApp.Models;

namespace PinterestApp.Controllers
{
    [Authorize(Roles = "User,Admin")]
    public class UsersController : Controller
    {

        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UsersController(
                                    ApplicationDbContext context,
                                    UserManager<ApplicationUser> userManager,
                                    RoleManager<IdentityRole> roleManager
                                   )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }


        public IActionResult Index()
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
                ViewBag.Alert = TempData["messageType"];
                ViewBag.Tip = TempData["messageIcon"].ToString();
            }

            var boards = db.Boards.Include("User").Include("SavedBookmarks.Bookmark").Include("SavedBookmarks.Bookmark.User").Where(b => b.UserId == _userManager.GetUserId(User));
            ViewBag.Boards = boards;
            var id = _userManager.GetUserId(User);
            var user = db.Users.Where(u=>u.Id == id).First();
            if (user.User_name == null)
            {
                user.User_name = _userManager.GetUserName(User);
                db.SaveChanges();
            }
            ViewBag.User = user;
            return View();
        }

        public IActionResult ViewUser(string id)
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
                ViewBag.Alert = TempData["messageType"];
                ViewBag.Tip = TempData["messageIcon"].ToString();
            }
            var user = db.Users.Where(u => u.Id == id).First();
            var username = user?.User_name;
            var boards = db.Boards.Include("User").Include("SavedBookmarks.Bookmark").Include("SavedBookmarks.Bookmark.User").Where(b => b.UserId == id);
            ViewBag.Boards = boards;
            ViewBag.Username = username;
            return View();
        }

        public IActionResult Edit(string id)  //id-ul user-ului care incearca sa intre
        {
            var user = db.Users.Where(u => u.Id == id).First();
            //am preluat userul cu id-ul trimis
            if(user.Id == _userManager.GetUserId(User))  //daca e acelasi ca cel curent
            {
                return View(user);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui profil care nu va apartine";
                TempData["messageType"] = "alert-danger";
                TempData["messageIcon"] = "0";
                return RedirectToAction("Index");
            }
        }

        //se adauga profilul modificat in baza de date
        [HttpPost]
        public IActionResult Edit(string id, ApplicationUser user) //id care e deja 
                //parametru la link + informatiile primite din get
        {
            //preluam user-ul care incearca sa intre
            var user1 = db.Users.Where(u => u.Id == id).First();
            if(ModelState.IsValid)   //daca s-a trecut de verificari
            {
                 if(user1.Id == _userManager.GetUserId(User)) //daca e user-ul bun
                {
                    user1.User_name = user.User_name;
                    db.SaveChanges();
                    TempData["message"] = "Ati editat cu succes board-ul";
                    TempData["messageType"] = "alert-success";
                    TempData["messageIcon"] = "1";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui board care nu va apartine";
                    TempData["messageType"] = "alert-danger";
                    TempData["messageIcon"] = "0";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(user);  //ne intoarcem in pagina de edit cu erori
            }
        }

    }
}

PinterestApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PinterestApp</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link rel="stylesheet" href="~/css/mycsstheme.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PinterestApp.styles.css" asp-append-version="true" />
    <!--summernote-->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
               <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PinterestApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookmarks" asp-action="Index">Bookmarks</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookmarks" asp-action="New">Adaugă Bookmark</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Boards" asp-action="Index">Boards</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Profil</a>
                            </li>
                        }
                        else
                        if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookmarks" asp-action="Index">Bookmarks</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookmarks" asp-action="New">Adaugă Bookmark</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Boards" asp-action="Index">Boards</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Profil</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookmarks" asp-action="Index">Bookmarks</a>
                            </li>
                        }
              
                    <partial name="_LoginPartial" /> 


                        <form action="/Bookmarks" class="search-container">
                            <form method="GET">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control"
                                           placeholder="Caută bookmark-uri" name="search"
                                           value="@ViewBag.SearchString">
                                    <button class="btn btn-secondary my-2 my-sm-0"
                                            type="submit">
                                        Caută
                                    </button>
                                </div>
                            </form>
                    </form>
                  
                </div>
            </div>
        </nav>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PinterestApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!--<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Summernote.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>