PinterestApp/Models/Bookmark.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PinterestApp.Models
{
    public class Bookmark
    {
        //cheia primara a entitatii bookmark
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage ="Titlul unui bookmark este obligatoriu!")]
        [StringLength(50, ErrorMessage = "Titlul unui bookmark nu poate depasi 50 de caractere!")]
        [MinLength(3, ErrorMessage = "Titlul unui bookmark trebuie sa aiba cel putin 3 caractere!")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Bookmark-ul trebuie sa aiba o descriere!" )]
        [MinLength(10, ErrorMessage ="Descrierea trebuie sa contina cel putin 10 caractere!" )]
        public string Description { get; set; }

        [Required(ErrorMessage ="Bookmark-ul trebuie sa aiba continut media!")]
        public string MediaContent { get; set; }
        public DateTime Date { get; set; }

        //un bookmark este postat de un user

        public string? UserId { get; set; }
        public virtual ApplicationUser? User { get; set; }


        //un bookmark are o colectie de comentarii
        public virtual ICollection<Comment>? Comments { get; set; }

        //un bookmark are o colectie de voturi
        public virtual ICollection<Vote>? Votes { get; set; }


        //relatia many to many dintre Bookmark si Board

        public virtual ICollection<SavedBookmark>? SavedBookmarks { get; set; }


    }
}

PinterestApp/Controllers/BookmarksController.cs
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PinterestApp.Data;
using PinterestApp.Models;

namespace PinterestApp.Controllers
{
    public class BookmarksController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public BookmarksController(
                                    ApplicationDbContext context,
                                    UserManager<ApplicationUser> userManager,
                                    RoleManager<IdentityRole> roleManager
                                   )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        //Si utilizatorii neinregistrati pot vizualiza bookmark-urile
        public IActionResult Index()
        {
            int _perPage = 5;
            var bookmarks = db.Bookmarks.Include("User").OrderByDescending(a => a.Votes.Count).ThenByDescending(a=>a.Date);
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
                ViewBag.Alert = TempData["messageType"];
                ViewBag.Tip = TempData["messageIcon"].ToString();
            }
            

            var search = "";
            // motor de cautare
            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim();
               
                //cautam bookmark-urile care contin string-ul
                List<int> bookmarkIds = db.Bookmarks.Where
                     (bm => bm.Title.Contains(search) || bm.Description.Contains(search)).Select(b => b.Id).ToList();
                bookmarks = db.Bookmarks.Where(bookmark => bookmarkIds.Contains(bookmark.Id))
                .Include("User")
                .OrderBy(b=>b.Title);
            }
            ViewBag.SearchString = search;


            int totalItems = bookmarks.Count();
            var currentPage =
            Convert.ToInt32(HttpContext.Request.Query["page"]);
            var offset = 0;
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }
            var paginatedBookmarks =
            bookmarks.Skip(offset).Take(_perPage);
            ViewBag.lastPage = Math.Ceiling((float)totalItems /
            (float)_perPage);
            ViewBag.Bookmarks = paginatedBookmarks;

            if (search != "")
            {
                ViewBag.PaginationBaseUrl = "/Bookmarks/Index/?search="
                + search + "&page";
            }
            else
            {
                ViewBag.PaginationBaseUrl = "/Bookmarks/Index/?page";
            }



            return View();
        }

        //Show - oricine poate vedea bookmark-urile in detaliu
        public IActionResult Show(int id)
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
                ViewBag.Alert = TempData["messageType"];
                ViewBag.Tip = TempData["messageIcon"].ToString();
            }
            Bookmark bookmark = db.Bookmarks.Include("Comments").Include("User").Include("Comments.User").Include("Votes").Include("Votes.User")
                               .Where(bm => bm.Id == id)
                               .First();
            var boards = db.Boards.Where(brd => brd.UserId == _userManager.GetUserId(User)).ToList();
            ViewBag.Boards = boards;
            SetAccessRights();
            UserVote(id);
            NumberOfVotes(bookmark.Id);
            return View(bookmark);
        }

        [HttpPost]
        [Authorize(Roles ="User")]
        public IActionResult Show([FromForm] Comment com)
        {
            com.Date = DateTime.Now;
            com.UserId = _userManager.GetUserId(User);
            if(ModelState.IsValid)
            {
                db.Comments.Add(com);
                db.SaveChanges();
                return Redirect("/Bookmarks/Show/" + com.BookmarkId);
            }
            else
            {
                Bookmark bookmark = db.Bookmarks.Include("User").Include("Comments").Include("Comments.User").Include("Votes").Include("Votes.User")
                                                .Where(bookmark => bookmark.Id == com.BookmarkId)
                                                .First();
                var boards = db.Boards.Where(brd => brd.UserId == _userManager.GetUserId(User)).ToList();
                ViewBag.Boards = boards;
                SetAccessRights();
                UserVote(bookmark.Id);
                NumberOfVotes(bookmark.Id);
                return View(bookmark);
            }
        }


        //New - doar utilizatorii inregistrati pot incarca bookmark-uri
        [Authorize(Roles = "User")]
        public IActionResult New()
        {
            return View();
        }

        // Se adauga bookmark-ul in baza de date
        [Authorize(Roles = "User")]
        [HttpPost]
        public IActionResult New(Bookmark bookmark)
        {
            //var sanitizer = new HtmlSanitizer();   //pentru editorul de text
            bookmark.UserId = _userManager.GetUserId(User);
            bookmark.Date = DateTime.Now;
            if(ModelState.IsValid)
            {
                //bookmark.MediaContent = sanitizer.Sanitize(bookmark.MediaContent);  //pentru editorul de text
                db.Bookmarks.Add(bookmark);
                db.SaveChanges();
                TempData["message"] = "Ati adaugat cu succes bookmark-ul!";
                TempData["messageType"] = "alert-success";
                TempData["messageIcon"] = "1";
                return RedirectToAction("Index");
            }
            else
            {
                return View(bookmark);
            }
        }



        //Edit - doar utilizatorii inregistrati pot edita bookmark-uri
        [Authorize(Roles = "User")]
        public IActionResult Edit(int id)
        {
            Bookmark bookmark = db.Bookmarks.Where(bm => bm.Id == id)
                                            .First();
            if(bookmark.UserId == _userManager.GetUserId(User))
            {
                return View(bookmark);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui bookmark care nu va apartine";
                TempData["messageType"] = "alert-danger";
                TempData["messageIcon"] = "0";
                return RedirectToAction("Index");
            }
        }


        [Authorize(Roles = "User")]
        // Se adauga bookmark-ul modificat in baza de date
        [HttpPost]
        public IActionResult Edit(int id, Bookmark bm)
        {
            //var sanitizer = new HtmlSanitizer();  //pentru editorul de text
            Bookmark bookmark = db.Bookmarks.Find(id);
            if (ModelState.IsValid)
            {
                if (bookmark.UserId == _userManager.GetUserId(User))
                {

                    bookmark.Title = bm.Title;
                    bookmark.Description = bm.Description;
                    //bm.MediaContent = sanitizer.Sanitize(bm.MediaContent);  //pentru editorul de text
                    bookmark.MediaContent = bm.MediaContent;
                    db.SaveChanges();
                    TempData["message"] = "Ati editat cu succes bookmark-ul";
                    TempData["messageType"] = "alert-success";
                    TempData["messageIcon"] = "1";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui bookmark care nu va apartine";
                    TempData["messageType"] = "alert-danger";
                    TempData["messageIcon"] = "0";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(bm);
            }
        }


        // Se sterge un bookmark din baza de date 
        [HttpPost]
        [Authorize(Roles ="User,Admin")]
        public ActionResult Delete(int id)
        {
            Bookmark bookmark = db.Bookmarks.Include("Comments")
                                            .Include("Votes")
                                            .Where(b=>b.Id==id)
                                            .First();
            if((bookmark.UserId==_userManager.GetUserId(User))||User.IsInRole("Admin"))
            {
                db.Bookmarks.Remove(bookmark);
                db.SaveChanges();
                TempData["message"] = "Ati sters cu succes bookmark-ul";
                TempData["messageType"] = "alert-success";
                TempData["messageIcon"] = "1";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul sa stergeti acest bookmark";
                TempData["messageType"] = "alert-danger";
                TempData["messageIcon"] = "0";
                return RedirectToAction("Index");
            }
            
        }
        [HttpPost]
        public IActionResult AddToBoard([FromForm] SavedBookmark savedBookmark)
        {
            if(ModelState.IsValid)
            {
                if(db.SavedBookmarks.Where(sb => sb.BookmarkId == savedBookmark.BookmarkId).Where(sb => sb.BoardId == savedBookmark.BoardId).Count()>0)
                {
                    TempData["message"] = "Ati adaugat deja acest bookmark in board-ul ales";
                    TempData["messageType"] = "alert-danger";

PinterestApp/Views/Bookmarks/Edit.cshtml
@model PinterestApp.Models.Bookmark

<form method="post" action="/Bookmarks/Edit/@Model.Id">

    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <label>Titlu bookmark:</label>
    @Html.EditorFor(m => m.Title, new { htmlAttributes = new { @class = "form-control" } })
    <p>@Html.ValidationMessage("Title", null, new { @class = "text-danger" })</p>
    <br /><br />

    <label>Descriere:</label>
    @Html.EditorFor(m => m.Description, new { htmlAttributes = new { @class = "form-control" } })
    <p>@Html.ValidationMessage("Description", null, new { @class = "text-danger" })</p>
    <br />

    <label>Continut:</label>
    @Html.TextArea("MediaContent", null, new { @class = "summernote" })
    <p>@Html.ValidationMessage("MediaContent", null, new { @class = "text-danger" })</p>
    <br />

    <br /><br />

    <button class="btn btn-success eu4" type="submit">Modifica bookmark</button>

</form>

PinterestApp/Views/Bookmarks/Index.cshtml
<h2 class="text-center">Afișare bookmark-uri</h2>
<br />
<br />

@if(TempData["message"]!=null)
{
    @if(ViewBag.Tip=="1")
    {
        <div class="alert @ViewBag.Alert p-3 rounded-3 text-center mb-5"><i class="bi bi-check-circle"></i>@ViewBag.message</div>
    }
    else
    {
        <div class="alert @ViewBag.Alert p-3 rounded-3 text-center mb-5"><i class="bi bi-exclamation-triangle-fill"></i>@ViewBag.message</div>
    }
}

@* search *@

@* <form method="GET">
    <div class="input-group mb-3">
        <input type="text" class="form-control"
               placeholder="Cautare" name="search"
               value="@ViewBag.SearchString">
        <button class="btn btn-outline-primary"
                type="submit">
            Search
        </button>
    </div>
</form> *@

@*Parcurgerea tuturor bookmark-urilor*@
@foreach (PinterestApp.Models.Bookmark bookmark in ViewBag.Bookmarks)
{
   
   <div class="card eu">

        <div class="card-body">

                <div class="card-text eu15" id="media-content">@Html.Raw(bookmark.MediaContent)</div>

                <h3 class="card-title alert-primary py-3 px-3 rounded-2">@bookmark.Title</h3>

                <div class="card-text">@bookmark.Description</div>

                <div class="d-flex justify-content-between flex-row mt-5">

                    <a class="btn btn-primary" href="/Bookmarks/Show/@bookmark.Id">Afisare bookmark</a>

                    <span class="alert-primary px-1 align-content-center">@bookmark.Date</span>
                    
                <a class="btn btn-primary" href="/Users/ViewUser/@bookmark.User.Id">@bookmark.User.UserName</a>

                </div>

        </div>

    </div>
    <br />
    <br />
}


@* Afisarea paginata a bookmark-urilor si in cazul in care se foloseste motorul de cautare *@
<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link"
                   href="@ViewBag.PaginationBaseUrl=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for (int i = 1; i <= ViewBag.lastPage; i++)
            {
                <li class="page-item">
                    <a class="page-link"
                       href="@ViewBag.PaginationBaseUrl=@i">@(i)</a>
                </li>
            }
            <li class="page-item">
                <a class="page-link"
                   href="@ViewBag.PaginationBaseUrl=@(ViewBag.lastPage)" aria-
                   label="Next">

                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

PinterestApp/Views/Bookmarks/New.cshtml
@model PinterestApp.Models.Bookmark

<h2>Adaugare bookmark</h2>
<br />

<form method="post" action="/Bookmarks/New">
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <label>Titlu bookmark:</label>
    @Html.EditorFor(m => m.Title, new { htmlAttributes = new { @class = "form-control" } })
    <p>@Html.ValidationMessage("Title", null, new { @class = "text-danger" })</p>
    <br />
    <br />

    <label>Descriere bookmark:</label>
    @Html.EditorFor(m => m.Description, new { htmlAttributes = new { @class = "form-control" } })
    <p>@Html.ValidationMessage("Description", null, new { @class = "text-danger" })</p>
    <br />
    <br />

    <label>Continut bookmark:</label>
    @Html.TextArea("MediaContent", null, new { @class = "summernote" })
    <p>@Html.ValidationMessage("MediaContent", null, new { @class = "text-danger" })</p>
    <div class="card-text"></div>
    <br />
    <br />

    <button class="btn eu8" type="submit">Adauga bookmark</button>

</form>

PinterestApp/Views/Bookmarks/Show.cshtml
@model PinterestApp.Models.Bookmark

@if (TempData["message"] != null)
{
    @if (ViewBag.Tip == "1")
    {
        <div class="alert @ViewBag.Alert p-3 rounded-3 text-center mb-5"><i class="bi bi-check-circle"></i>@ViewBag.message</div>
    }
    else
    {
        <div class="alert @ViewBag.Alert p-3 rounded-3 text-center mb-5"><i class="bi bi-exclamation-triangle-fill"></i>@ViewBag.message</div>
    }
}



<div class="card">

    <div class="card-body">
        <div class="card-text">@Html.Raw(Model.MediaContent)</div>

        <h3 class="card-title alert-primary py-3 px-3 rounded-2">@Model.Title</h3>

        <div class="card-text">@Model.Description</div>

        <div class="d-flex justify-content-between flex-row mt-5">

            <span class="alert-primary">@Model.Date</span>

            <a class="btn btn-primary" href="/Users/ViewUser/@Model.User.Id">@Model.User.UserName</a>

        </div>

    </div>

    <hr />

    @if (ViewBag.AfisareButoane == true && Model.UserId == ViewBag.UserCurent || ViewBag.EsteAdmin)
    {
        <div class="d-flex flex-row justify-content-between">

        <a class="btn eu7" href="/Bookmarks/Edit/@Model.Id">Editeaza bookmark</a>

        <div class="d-flex flex-row justify-content-between">

            <form method="post" action="/Bookmarks/Delete/@Model.Id">

                <button class="btn eu8" type="submit">Sterge bookmark</button>

            </form>

        </div>

    </div>
    }
    <br />
    <br />

    <div class="d-flex flex-row justify-content-between">
        @if (ViewBag.AfisareButoane == true)
        {

            @if (ViewBag.Vote == false)
            {
                <form method="post" action="/Votes/New">
                    <input type="hidden" name="BookmarkId" value="@Model.Id"></input>
                    <button class="btn btn-primary eu9" type="submit"><i class="bi bi-star"></i></button>
                </form>
            }
            else
            {
                <form method="post" action="/Votes/Delete/@ViewBag.VoteId">
                    <button class="btn btn-primary eu9" type="submit"><i class="bi bi-star-fill"></i></button>
                </form>
            }

        }
        <div><p class="eu10">Aprecieri: @ViewBag.NumberOfVotes</p></div>
    </div>

    <form method="post" asp-controller="Bookmarks" asp-action="AddToBoard">
        <input type="hidden" name="BookmarkId" value="@Model.Id" />
        <div class="d-flex flex-row justify-content-center p-3 border-1 border-top eu5">
            <div>
                <select name="BoardId" class="form-controll">
                    <option selected>Salveaza!</option>
                    @foreach(var board in ViewBag.Boards)
                    {
                        <option value="@board.Id">@board.Title</option>
                    }
                </select>
            </div>
            <div>
                <input type="submit" class="btn btn-success alert-success eu6" value="+" />
            </div>

        </div>
    </form>

</div>

<br />
<br />


@if (TempData["message"] != null)
{
    @if (ViewBag.Tip == "1")
    {
        
        <div class="alert @ViewBag.Alert p-3 rounded-3 text-center mb-5"><i class="bi bi-check-circle"></i>@ViewBag.message</div>
    }
    else
    {
        <div class="alert @ViewBag.Alert p-3 rounded-3 text-center mb-5"><i class="bi bi-exclamation-triangle-fill"></i>@ViewBag.message</div>
    }
}

@*Imi afisez comentariile pentru fiecare articol*@

@foreach (var com in Model.Comments)
{
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div>
                    <p>@com.Content</p>
                    <small>@com.Date</small>
                    <small>@com.User.UserName</small>
                </div>
                <br />
                <div class="d-flex flex-row justify-content-between">
                @if (ViewBag.AfisareButoane == true && com.UserId == ViewBag.UserCurent)
                {
                        <div>
                        <a class="btn btn-outline-warning" href="/Comments/Edit/@com.Id"><i class="bi bi-pencil"></i>Editare</a>
                    </div>
                }
                @if (ViewBag.AfisareButoane == true && com.UserId == ViewBag.UserCurent || ViewBag.EsteAdmin)
                {
                    <form method="post" action="/Comments/Delete/@com.Id">

                        <button class="btn btn-outline-danger" type="submit"><i class="bi bi-eraser"></i>Sterge</button>

                    </form>
                }
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
}
<br />

@*Afisez formularul de adaugare a unui nou comentariu*@

<div class="container">

    <div class="row">

        <div class="col-md-2"></div>

        <div class="col-md-8">

            <div class="card">

                <form method="post" action="/Bookmarks/Show/@Model.Id">

                    <div class="card-body">

                        <input type="hidden" name="BookmarkId" value="@Model.Id" />

                        <label>Continut comentariu</label>
                        <br />

                        <textarea class="form-control" name="Content"></textarea>

                        @Html.ValidationMessage("Content", null, new { @class = "text-danger"})

                        <br />

                        <button class="btn btn-primary" type="submit">Adauga comentariul</button>

                    </div>

                </form>

            </div>

        </div>

        <div class="col-md-2"></div>

    </div>

</div>